### ISSUE TITLE
Allow setting mermaid theme (and other options) in logseq-fenced-code-plus.json

### ISSUE THREAD

**Issue by DanielPower** [benjypng/logseq-mermaid-plugin#14]
Currently a mermaid theme can be set per block:
\`\`\`mermaid
%%{init: {'theme':'forest'}}%%
graph TD;
  A-->B;
\`\`\`

It would be helpful if we could set the default theme in the plugin's config.json, so that we can set the theme for all code blocks in one place.

**Comment by benjypng** [comment]
I believe your suggestion applies to [another plugin](https://github.com/xyhp915/logseq-fenced-code-plus).

**Comment by DanielPower** [comment]
You're right. Sorry about that!
