### ISSUE TITLE
Allow setting host URL completely, not only the port

### ISSUE THREAD

**Issue by ivan-danilov** [benjypng/logseq-mermaid-plugin#15]
It would be nice to be able to replace the scheme and host in the settings. After all, the current (`http://localhost:${port}`)[https://github.com/hkgnp/logseq-mermaid-plugin/blob/master/src/convert.ts#L41] could be https, not localhost, etc.

It is easy to set up a container or an RPI with a mermaid server available on the local network 24/7/365. You don't need to dance with locally running processes every time you need to render something. On the other hand, using localhost remains the same.

**Comment by benjypng** [comment]
Fixed in latest version.
