### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initialize')

### ISSUE THREAD

**Issue by cemsbr** [benjypng/logseq-mermaid-plugin#20]
The plugin is not working for me. Logseq version: 0.10.9. Maybe this error is the cause.

![image](https://github.com/user-attachments/assets/0b46eb74-4ef9-4f65-8c1e-63bdc4d5dc9f)

Source code:

![image](https://github.com/user-attachments/assets/591d7967-3cbe-4d6a-946f-605e3d36504d)

**Comment by benjypng** [comment]
Fixed in latest version.
